#!/usr/bin/env bash
#
# LUKE AI STUDIO - bring this checkout up to date without losing anything
#
# Run this instead of `git pull --ff-only`.
#
# Why it exists: the app runs from a git checkout on your own disk and rewrites
# its own state while you use it. `scripts/setup/git-local-state.sh` marks those
# files "skip-worktree" so git stops comparing them, which keeps ordinary usage
# quiet - but skip-worktree does not survive an update that touches one of those
# files. When that happens a plain `git pull --ff-only` stops with
#
#   error: Your local changes to the following files would be overwritten by merge
#
# and the usual remedy, `git checkout -- <file>`, does not work either: git
# refuses to match a skip-worktree path and answers
#
#   error: pathspec '...' did not match any file(s) known to git
#
# Worse, git abandons the whole checkout if any one pathspec fails, so a command
# listing several files restores none of them.
#
# This script does the sequence in the order that works, one file at a time:
# clear the flags, discard machine state, pull, and put back anything that is
# actually yours. Machine state is regenerated by the app on the next boot.
#
# Usage:  bash sync.sh            update, then stop
#         bash sync.sh --run      update, then launch the app

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR" || exit 1

if ! command -v git >/dev/null 2>&1; then
  echo "  [sync] git is not available; nothing to do." >&2
  exit 1
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "  [sync] this folder is not a git checkout." >&2
  exit 1
fi

# Yours, not the machine's. These are never discarded: if the update would
# remove or replace one, the copy taken below is put back afterwards. The
# image-to-video record files are this machine's install record; they are
# untracked now, and the copy taken below is what carries a local install
# through the update that stops tracking them.
PROTECTED=(
  "app/runtime-state/text-chat/conversations.json"
  "app/runtime-state/text-chat/model-feedback.json"
  "app/runtimes/image-to-video/installed.json"
  "app/runtimes/image-to-video/install-status.json"
)

# Whole folders that are yours. `releases/` holds what the release scripts
# produce — build output, not source — so it is untracked and ignored, and an
# update that stops tracking it would delete every copy on this machine.
PROTECTED_DIRS=(
  "releases"
)

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
if [[ -z "$BRANCH" || "$BRANCH" == "HEAD" ]]; then
  echo "  [sync] detached HEAD; check out your branch first." >&2
  exit 1
fi

echo "  [sync] branch: $BRANCH"

# ── 1. take a copy of anything that is yours ────────────────────────────────

BACKUP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/luke-sync-XXXXXX")"
trap 'rm -rf "$BACKUP_DIR"' EXIT

backed_up=0
for entry in "${PROTECTED[@]}"; do
  if [[ -f "$entry" ]]; then
    mkdir -p "$BACKUP_DIR/$(dirname "$entry")"
    cp -p "$entry" "$BACKUP_DIR/$entry"

    # Step 3 discards local changes on the strength of this copy, so a copy
    # that did not land has to stop the script rather than be trusted.
    if ! cmp -s "$entry" "$BACKUP_DIR/$entry"; then
      echo "  [sync] could not copy $entry aside; stopping before changing anything." >&2
      exit 1
    fi

    backed_up=$((backed_up + 1))
  fi
done

for entry in "${PROTECTED_DIRS[@]}"; do
  if [[ -d "$entry" ]]; then
    mkdir -p "$BACKUP_DIR/$entry"
    cp -Rp "$entry/." "$BACKUP_DIR/$entry/"
    backed_up=$((backed_up + 1))
  fi
done

if [[ "$backed_up" -gt 0 ]]; then
  echo "  [sync] copied $backed_up file(s) of yours aside, and checked the copy"
fi

# ── 2. clear skip-worktree so git will look at these files again ─────────────
#
# Without this, step 3 cannot restore them and step 4 refuses the update.

cleared=0
while IFS= read -r -d '' file; do
  [[ -n "$file" ]] || continue
  if git ls-files -v -- "$file" | grep -q '^S '; then
    git update-index --no-skip-worktree -- "$file" >/dev/null 2>&1 && cleared=$((cleared + 1))
  fi
done < <(git ls-files -z -- app/runtime-state 2>/dev/null)

if [[ "$cleared" -gt 0 ]]; then
  echo "  [sync] released $cleared machine-state file(s) git was told to ignore"
fi

# ── 3. discard local changes, one file at a time ─────────────────────────────
#
# Deliberately not `git checkout -- app/runtime-state`: a single unmatched
# pathspec aborts the whole command and restores nothing, which is how a
# five-file remedy once fixed none of the five.
#
# The protected files are discarded here too, on the strength of the checked
# copy from step 1 - leaving them modified would let them block step 4 just as
# easily as any other file, and step 5 puts their contents back.

state_files=()
while IFS= read -r -d '' file; do
  [[ -n "$file" ]] || continue
  state_files+=("$file")
done < <(git ls-files -z -- app/runtime-state 2>/dev/null)

# A protected file that is still tracked - the middle of the untrack
# transition - blocks the merge the same way any modified file would, so it
# is discarded here too, on the strength of the checked copy from step 1.
for entry in "${PROTECTED[@]}"; do
  if git ls-files --error-unmatch -- "$entry" >/dev/null 2>&1; then
    state_files+=("$entry")
  fi
done

discarded=0
if [[ "${#state_files[@]}" -gt 0 ]]; then
  for file in "${state_files[@]}"; do
    [[ -n "$file" ]] || continue
    if [[ -n "$(git status --porcelain -- "$file" 2>/dev/null)" ]]; then
      git checkout -- "$file" >/dev/null 2>&1 && discarded=$((discarded + 1))
    fi
  done
fi

if [[ "$discarded" -gt 0 ]]; then
  echo "  [sync] discarded local changes in $discarded state file(s) - the app rewrites these on boot"
fi

# ── 4. the update itself ─────────────────────────────────────────────────────

git fetch --quiet origin "$BRANCH" || {
  echo "  [sync] could not reach origin; leaving the checkout as it is." >&2
  exit 1
}

BEFORE="$(git rev-parse --short HEAD)"

if ! git merge --ff-only "origin/$BRANCH"; then
  echo "" >&2
  echo "  [sync] the update did not fast-forward. Nothing was discarded twice -" >&2
  echo "         your files are still here. Show me the message above." >&2
  exit 1
fi

AFTER="$(git rev-parse --short HEAD)"

if [[ "$BEFORE" == "$AFTER" ]]; then
  echo "  [sync] already up to date ($AFTER)"
else
  echo "  [sync] updated $BEFORE -> $AFTER"
fi

# ── 5. put back anything that is yours ───────────────────────────────────────
#
# An update that stops tracking one of these deletes it from the working tree.
# That is correct for machine state and unacceptable for your chat history, so
# the copy from step 1 wins.

restored=0
for entry in "${PROTECTED[@]}"; do
  if [[ -f "$BACKUP_DIR/$entry" ]]; then
    mkdir -p "$(dirname "$entry")"
    if [[ ! -f "$entry" ]] || ! cmp -s "$BACKUP_DIR/$entry" "$entry"; then
      cp -p "$BACKUP_DIR/$entry" "$entry"
      restored=$((restored + 1))
    fi
  fi
done

for entry in "${PROTECTED_DIRS[@]}"; do
  if [[ -d "$BACKUP_DIR/$entry" ]]; then
    mkdir -p "$entry"
    # Put back what the update removed, without overwriting what it brought.
    while IFS= read -r -d '' relative; do
      if [[ ! -e "$entry/$relative" ]]; then
        mkdir -p "$entry/$(dirname "$relative")"
        cp -p "$BACKUP_DIR/$entry/$relative" "$entry/$relative"
        restored=$((restored + 1))
      fi
    done < <(cd "$BACKUP_DIR/$entry" && find . -type f -print0 | sed -z 's|^\./||')
  fi
done

if [[ "$restored" -gt 0 ]]; then
  echo "  [sync] put $restored file(s) of yours back"
fi

# Step 2 released the skip-worktree flags and this script does not put them
# back, so `git status` will now show machine state the app has written. That is
# deliberate: with the flags set, git hides those changes and then refuses an
# update that touches them, and `git checkout -- <file>` cannot clear it because
# git will not match a skip-worktree path. Without them every ordinary git
# remedy works. `bash mac.sh` sets them again on the next launch.

echo "  [sync] done."

if [[ "${1:-}" == "--run" ]]; then
  echo ""
  exec bash "$SCRIPT_DIR/mac.sh"
fi
